name: Build and Test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x" # ajuste conforme sua versão (ex: 8.0.x)

      - name: Restaurar dependências
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Rodar testes
        run: dotnet test --no-build --configuration Release --verbosity normal
